"""
SPX Live Engine — Layer B AI Interpretation Engine (DeepSeek API Integration)
Receives immutable Evidence Packet from Layer A, queries DeepSeek API, and validates JSON schema.
"""

import json
import logging
import requests
from typing import Dict, Any, Optional

logger = logging.getLogger("spx_engine.ai_interpreter")

SYSTEM_PROMPT = """
You are interpreting a verified SPX Market Evidence Packet generated by a deterministic financial market engine.
Your role is strictly interpretation, context explanation, conflict summary, and invalidation condition identification.

STRICT OPERATIONAL RULES:
1. NEVER invent or fabricate market prices, VWAP values, highs, lows, market breadth, VIX changes, or indicator values.
2. NEVER override the deterministic market_state, direction, or numerical scores passed in the Evidence Packet.
3. If data is missing or unavailable, explicitly state "DATA UNAVAILABLE".
4. State what changed clearly compared to prior state.
5. Explain what would confirm or invalidate the current setup.
6. Output ONLY valid JSON matching this exact JSON schema:

{
  "market_state": "CONFIRMED_LONG",
  "direction": "LONG",
  "confidence": 82,
  "summary": "Brief executive summary of market conditions",
  "supporting_factors": ["Factor 1", "Factor 2"],
  "conflicting_factors": ["Conflict 1"],
  "what_changed": ["Change 1", "Change 2"],
  "confirmation_needed": ["Condition 1"],
  "invalidation_conditions": ["Condition 1"],
  "risk_notes": ["Note 1"]
}
"""

class SPXAIInterpreter:
    def __init__(self, deepseek_api_key: Optional[str] = None):
        self.api_key = deepseek_api_key
        self.api_url = "https://api.deepseek.com/v1/chat/completions"

    def build_evidence_packet(self, snapshot: dict) -> dict:
        return {
            "evidence_version": "2.1",
            "timestamp_et": snapshot.get("timestamp"),
            "session_phase": snapshot.get("session_phase"),
            "macro_state": snapshot.get("macro_state"),
            "spx": snapshot.get("spx", {}),
            "es": snapshot.get("es", {}),
            "es_spx_basis": snapshot.get("es_spx_basis", 0.0),
            "nq": snapshot.get("nq", {}),
            "vix": snapshot.get("vix", {}),
            "breadth": snapshot.get("breadth", {}),
            "scores": {
                "long": snapshot.get("long_score"),
                "short": snapshot.get("short_score"),
                "net": snapshot.get("net_score"),
                "confidence_tier": snapshot.get("confidence_tier")
            },
            "state": snapshot.get("state")
        }

    def request_ai_interpretation(self, snapshot: dict) -> Optional[dict]:
        packet = self.build_evidence_packet(snapshot)
        
        if not self.api_key:
            logger.warning("No DeepSeek API key provided. Returning fallback deterministic explanation.")
            return self._generate_fallback_response(packet)

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        payload = {
            "model": "deepseek-chat",
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"EVIDENCE PACKET:\n{json.dumps(packet, indent=2)}"}
            ],
            "temperature": 0.2,
            "max_tokens": 800
        }

        try:
            resp = requests.post(self.api_url, headers=headers, json=payload, timeout=12)
            if resp.status_code == 200:
                content = resp.json()["choices"][0]["message"]["content"]
                content_clean = content.replace("```json", "").replace("```", "").strip()
                parsed = json.loads(content_clean)
                return parsed
            else:
                logger.error(f"DeepSeek API Error HTTP {resp.status_code}: {resp.text}")
                return self._generate_fallback_response(packet)
        except Exception as e:
            logger.error(f"Failed to query DeepSeek API: {e}")
            return self._generate_fallback_response(packet)

    def _generate_fallback_response(self, packet: dict) -> dict:
        state = packet.get("state", "NEUTRAL")
        scores = packet.get("scores", {})
        return {
            "market_state": state,
            "direction": "LONG" if scores.get("net", 0) > 0 else ("SHORT" if scores.get("net", 0) < 0 else "NEUTRAL"),
            "confidence": 80 if packet.get("scores", {}).get("confidence_tier") in ("HIGH", "VERY_HIGH") else 50,
            "summary": f"Deterministic Engine state is {state} with NetScore {scores.get('net', 0)}.",
            "supporting_factors": [f"Deterministic Score: Long {scores.get('long')}, Short {scores.get('short')}"],
            "conflicting_factors": [],
            "what_changed": [f"Session Phase: {packet.get('session_phase')}"],
            "confirmation_needed": ["Continued ES structure alignment"],
            "invalidation_conditions": ["Loss of Session VWAP or structure break"],
            "risk_notes": ["Evaluated deterministically by Layer A"]
        }
