import MemberHeader from "@/components/public/MemberHeader";
import Footer from "@/components/Footer";
import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#0d1117]">
      <MemberHeader locale="en" />

      <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-16">
        
        <h1 className="text-3xl font-semibold text-white mb-8 tracking-tight">Legal Disclaimers, Liability Waiver & Regulatory Compliance Statement</h1>

        <div className="glass-card p-8 space-y-12 text-white leading-relaxed">
          {/* Section 1 */}
          <section>
            <h2 className="text-lg font-medium text-white mb-4">1. No Investment Advice Disclaimer (Not Financial Advice)</h2>
            <p className="mb-4">
              BOGASTOCK.com (Blue One Global Analysis) is an automated financial analysis, research, and educational platform utilizing quantitative data models, proprietary algorithms, and artificial intelligence. All content, tools, metrics, scores, ratings, and classifications generated by our proprietary AI scoring engine (including but not limited to designations such as "HIGH CONVICTION," "POSITIVE BIAS," "BULLISH", etc.) are provided solely for general informational and educational purposes.
            </p>
            <p className="mb-4">
              <strong>No Fiduciary Relationship:</strong> Under no circumstances does any information, analysis, or signal provided on this platform constitute investment, financial, legal, or tax advice. BOGASTOCK.com is not registered as an Investment Adviser, Broker-Dealer, or Financial Fiduciary under any regulatory framework across the jurisdictions we serve. Specifically:
            </p>
            <ul className="list-disc list-inside mb-4 space-y-2">
              <li><strong>United States:</strong> We are not a Registered Investment Adviser (RIA) or Broker-Dealer under the U.S. Investment Advisers Act of 1940 or SEC rules. No fiduciary duty is established.</li>
              <li><strong>Canada:</strong> We do not act as registered advisors or dealers under any provincial Securities Commission (e.g., OSC, ASC, BCSC).</li>
              <li><strong>United Kingdom:</strong> We do not provide regulated advice or carry out any regulated activities under the Financial Services and Markets Act 2000 (FSMA) or FCA rules.</li>
              <li><strong>Australia:</strong> We do not hold an Australian Financial Services Licence (AFSL) under the Corporations Act 2001 (Cth) and do not provide personal financial advice.</li>
              <li><strong>South Korea:</strong> We do not conduct "discretionary investment business" or "investment advisory business" under the Financial Investment Services and Capital Markets Act (FSCMA).</li>
              <li><strong>India:</strong> We are not registered with the Securities and Exchange Board of India (SEBI) as a Research Analyst or Investment Adviser under the SEBI (Investment Advisers) Regulations, 2013.</li>
              <li><strong>Southeast Asia (Indonesia & Malaysia):</strong> We are not licensed financial advisors or investment representatives under the Indonesian Financial Services Authority (OJK) or the Securities Commission Malaysia (SCM) under the Capital Markets and Services Act 2007 (CMSA).</li>
            </ul>
            <p>
              You must not rely on BOGASTOCK.com to make any financial decisions. You are solely responsible for conducting your own independent research and consulting with a licensed, certified financial professional before making any investment.
            </p>
          </section>

          {/* Section 2 */}
          <section>
            <h2 className="text-lg font-medium text-white mb-4">2. High-Risk Warning & Comprehensive Waiver of Liability</h2>
            <p className="mb-4">
              Trading securities, equities, options, and other financial instruments in global capital markets—including but not limited to United States (NYSE, NASDAQ), Canadian (TSX), United Kingdom (LSE), Australian (ASX), South Korean (KRX), Indian (NSE, BSE), Malaysian (Bursa Malaysia), and Indonesian (IDX) exchanges—carries an exceptionally high level of risk. This volatility can result in the rapid and total loss of all invested capital.
            </p>
            <p className="mb-4">
              <strong>Past Performance is No Guarantee:</strong> The algorithms, indicators, and AI scores displayed on this platform are experimental, speculative, and derived from historical data models. Past statistical performance is not indicative of future results or actual market conditions. We make no representations, warranties, or guarantees (express or implied) regarding the profitability, accuracy, completeness, or reliability of our data.
            </p>
            <p>
              <strong>Investor Assumption of Risk:</strong> By using this platform, you acknowledge that any investment decisions or trades you execute based on BOGASTOCK.com analyses are made at your own exclusive risk and discretion. You hereby release, hold harmless, and waive BOGASTOCK.com, its parent companies, founders, employees, and affiliates from any and all liability for any direct, indirect, incidental, or consequential financial losses, damages, or costs resulting from your use of this service.
            </p>
          </section>

          {/* Section 3 */}
          <section>
            <h2 className="text-lg font-medium text-white mb-4">3. Data Privacy & Global Regulatory Compliance (GDPR, CCPA, KVKK, PDPB, SPDI)</h2>
            <p className="mb-4">
              BOGASTOCK.com is fully committed to safeguarding user data in strict compliance with global privacy regulations, including but not limited to the European Union and UK General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), Canada's Personal Information Protection and Electronic Documents Act (PIPEDA), Turkey's Personal Data Protection Law No. 6698 (KVKK), South Korea's Personal Information Protection Act (PIPA), India's Digital Personal Data Protection Act (DPDP), Australia's Privacy Act 1988, and equivalent laws in Malaysia (PDPA 2010) and Indonesia (PDP Law).
            </p>
            <ul className="list-disc list-inside mb-4 space-y-2">
              <li><strong>Data Collection:</strong> We collect only minimal essential data (such as email addresses) strictly for secure user authentication, account verification, and subscription management via trusted, secure third-party identity providers.</li>
              <li><strong>No Data Selling:</strong> BOGASTOCK.com does not sell, lease, or monetize your personal data to any third-party data brokers or advertisers.</li>
              <li><strong>User Rights:</strong> Users maintain complete ownership of their data. You have the right to request the deletion ("Right to be Forgotten"), modification, or extraction of your personal records at any time through your account settings or by contacting our support team.</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section>
            <h2 className="text-lg font-medium text-white mb-4">4. Advertising, Independence & Objectivity</h2>
            <p>
              To maintain operational viability and offer free-tier access, BOGASTOCK.com may display third-party advertisements. We maintain a strict and absolute separation between our advertising networks and our quantitative scoring models. Third-party advertisers, sponsors, or partners have zero influence, input, or control over the BOGASTOCK.com AI scoring engine, signal generation, or stock selection algorithms. All analytical outputs are generated purely through objective, programmatically executed mathematical parameters.
            </p>
          </section>

          {/* Section 5 */}
          <section>
            <h2 className="text-lg font-medium text-white mb-4">Investor Agreement</h2>
            <p>
              By accessing, subscribing to, or utilizing BOGASTOCK.com (Blue One Global Analysis), you explicitly acknowledge that you have read, understood, and voluntarily agreed to be bound by all of the legal conditions, jurisdictional disclaimers, liability waivers, and privacy policies outlined above.
            </p>
          </section>

          <section className="pt-8 border-t border-[#1e2a3a]">
            <p className="text-sm italic font-medium text-[#00d2ff]">
              Effective Date: May 1, 2026<br/>
              Jurisdictions Covered: United States, Canada, United Kingdom, Australia, South Korea, Indonesia, Malaysia, India, and Global Financial Markets.
            </p>
          </section>
        </div>
      </main>

      <Footer hidePlatform={true} locale="en" />
    </div>
  );
}
