-- "BOGA View" verdict block (bias/confidence/confirmation/risk) added to the
-- market_picture card. Computed deterministically in code from `facts`
-- (see lib/marketBiasEngine.ts) — never generated by the AI narrative.

alter table public.market_picture add column if not exists boga_view jsonb;
