import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-t border-[#1e2a3a] bg-[#0a0e17] mt-12">
      {/* Disclaimer */}
      <div className="bg-[#141924] border-b border-[#1e2a3a] px-6 py-5">
        <div className="max-w-5xl mx-auto text-center space-y-2">
          <p className="text-sm text-[#94a3b8] font-semibold uppercase tracking-widest">⚠ Important Risk Disclosure</p>
          <p className="text-xs text-[#64748b] leading-relaxed">
            <strong className="text-[#94a3b8]">FinMA Daily +500 is strictly for informational and educational purposes only.</strong>{" "}
            Nothing on this platform constitutes financial, investment, legal, or tax advice of any kind. All FinMA AI scores, ratings, and
            analysis are generated by automated algorithms and are experimental in nature — they do not represent the views of a licensed
            financial advisor or registered investment professional. Trading and investing in US equities, options, or any financial instrument
            involves substantial risk of loss, including the possible loss of your entire principal. Past performance, backtested results,
            or historical scores are not indicative of future results and should not be relied upon when making investment decisions.
            FinMA does not guarantee the accuracy, completeness, or timeliness of any data or analysis provided.
            By using this platform you acknowledge you have read, understood, and agreed to all terms.{" "}
            <Link href="/disclaimer" className="text-[#3b82f6] hover:underline font-semibold">
              Read full Legal &amp; Compliance disclosure →
            </Link>
          </p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div className="relative w-8 h-8">
                <img src="/finmawave.png" alt="FinMA" className="w-full h-full object-contain rounded-lg" />
              </div>
              <span className="text-base font-black text-white tracking-tighter">FinMA Daily +500</span>
            </div>
            <p className="text-xs text-[#64748b]">
              AI-powered daily analysis of +500 top US stocks.
            </p>
          </div>

          {/* Categories */}
          <div>
            <h4 className="text-sm font-semibold text-[#94a3b8] mb-3">Categories</h4>
            <div className="flex flex-col gap-1.5">
              <Link href="/category/top-scores" className="text-xs text-[#64748b] hover:text-white transition-colors">Top Scores</Link>
              <Link href="/category/breakout" className="text-xs text-[#64748b] hover:text-white transition-colors">Breakout</Link>
              <Link href="/category/undervalued" className="text-xs text-[#64748b] hover:text-white transition-colors">Undervalued</Link>
              <Link href="/category/momentum" className="text-xs text-[#64748b] hover:text-white transition-colors">Momentum</Link>
              <Link href="/category/reversal" className="text-xs text-[#64748b] hover:text-white transition-colors">Reversal</Link>
              <Link href="/category/dividend" className="text-xs text-[#64748b] hover:text-white transition-colors">Dividend</Link>
            </div>
          </div>

          {/* Resources */}
          <div>
            <h4 className="text-sm font-semibold text-[#94a3b8] mb-3">Resources</h4>
            <div className="flex flex-col gap-1.5">
              <Link href="/about" className="text-xs text-[#64748b] hover:text-white transition-colors">About FinMA</Link>
              <Link href="/archive" className="text-xs text-[#64748b] hover:text-white transition-colors">Archive</Link>
              <Link href="/contact" className="text-xs text-[#64748b] hover:text-white transition-colors">Contact</Link>
            </div>
          </div>

          {/* Legal */}
          <div>
            <h4 className="text-sm font-semibold text-[#94a3b8] mb-3">Legal</h4>
            <div className="flex flex-col gap-1.5">
              <Link href="/disclaimer" className="text-xs text-[#64748b] hover:text-white transition-colors">Disclaimer</Link>
              <Link href="/terms" className="text-xs text-[#64748b] hover:text-white transition-colors">Terms of Service</Link>
              <Link href="/privacy" className="text-xs text-[#64748b] hover:text-white transition-colors">Privacy Policy</Link>
            </div>
          </div>
        </div>

        <div className="border-t border-[#1e2a3a] mt-8 pt-4 text-center">
          <p className="text-xs text-[#64748b]">
            &copy; 2026 FinMA Daily +500. Developed by AFK DaSYS.
          </p>
        </div>
      </div>
    </footer>
  );
}
