"use client";

import Link from "next/link";
import { formatPrice } from "@/lib/data";

interface SwingPick {
  rank: number;
  ticker: string;
  company: string;
  score: number;
  current_price: number;
  buy_zone: { low: number; high: number };
  profit_zone: { low: number; high: number };
  stop_zone: { low: number; high: number };
  rvol: number;
  adx: number;
  rsi: number;
  pattern: string;
  market_regime: string;
  holding_period: string;
}

interface Props {
  picks: SwingPick[];
}

export default function TopSwingPicks({ picks }: Props) {
  if (!picks || picks.length === 0) return null;

  return (
    <div className="py-10">
      <div className="flex items-center gap-4 mb-8">
        <div className="relative">
          <div className="absolute -inset-1 rounded-full blur opacity-60 bg-[#ec4899]"></div>
          <div className="w-2 h-10 bg-[#ec4899] rounded-full relative"></div>
        </div>
        <div>
          <h2 className="text-3xl font-black text-white tracking-tighter uppercase italic">
            Top 3 Swing Picks
          </h2>
          <p className="text-[#94a3b8] text-sm mt-1">Generated by BOGA Swing Engine</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {picks.map((item, idx) => {
          const medals = ["bg-gradient-to-br from-[#ec4899] to-[#be185d]",
                          "bg-gradient-to-br from-[#94a3b8] to-[#64748b]",
                          "bg-gradient-to-br from-[#d97706] to-[#92400e]"];
          return (
            <Link
              key={item.ticker}
              href={`/stock/${item.ticker}`}
              className="glass-card p-6 hover:bg-[#1a2030] transition-all duration-300 group relative overflow-hidden border-2 border-transparent hover:border-[#ec4899]/20"
            >
              {/* Rank badge */}
              <div className={`absolute top-0 right-0 w-14 h-14 rounded-bl-3xl flex items-center justify-center text-lg font-black text-white shadow-2xl ${medals[idx]}`}>
                #{idx + 1}
              </div>

              {/* Ticker & Company */}
              <div className="mb-4">
                <div className="text-4xl font-black text-white group-hover:text-[#ec4899] transition-colors tracking-tighter uppercase">
                  {item.ticker}
                </div>
                <div className="text-sm font-bold text-[#64748b] tracking-wider mt-1 line-clamp-1">
                   {item.company}
                </div>
              </div>

              {/* Score + Pattern */}
              <div className="flex flex-col gap-3 mb-6">
                <div className="flex items-end gap-2">
                   <div className="text-5xl font-mono font-black text-[#ec4899] leading-none">
                     {item.score.toFixed(1)}
                   </div>
                   <div className="text-[9px] text-[#64748b] font-black uppercase tracking-[0.2em] mb-1">SWING SCORE</div>
                </div>
                <div className="flex">
                  <span className={`px-4 py-1.5 rounded-2xl text-[10px] font-black uppercase tracking-wider shadow-xl bg-[#ec4899]/20 text-[#fbcfe8] border border-[#ec4899]/40`}>
                    {item.pattern}
                  </span>
                </div>
              </div>

              {/* Zones */}
              <div className="mb-6 bg-black/30 rounded-xl p-4 border border-white/5">
                 <div className="grid grid-cols-2 gap-4 gap-y-6">
                   <div>
                     <div className="text-[10px] text-[#64748b] font-black uppercase tracking-wider mb-1 flex items-center gap-1">
                       <span className="w-1.5 h-1.5 rounded-full bg-[#3b82f6]"></span>
                       BUY ZONE
                     </div>
                     <div className="text-sm font-mono font-bold text-white">
                       {formatPrice(item.buy_zone.low)} - {formatPrice(item.buy_zone.high)}
                     </div>
                   </div>
                   
                   <div>
                     <div className="text-[10px] text-[#64748b] font-black uppercase tracking-wider mb-1 flex items-center gap-1">
                       <span className="w-1.5 h-1.5 rounded-full bg-[#10b981]"></span>
                       PROFIT ZONE
                     </div>
                     <div className="text-sm font-mono font-bold text-[#10b981]">
                       {formatPrice(item.profit_zone.low)} - {formatPrice(item.profit_zone.high)}
                     </div>
                   </div>

                   <div>
                     <div className="text-[10px] text-[#64748b] font-black uppercase tracking-wider mb-1 flex items-center gap-1">
                       <span className="w-1.5 h-1.5 rounded-full bg-[#ef4444]"></span>
                       STOP LOSS
                     </div>
                     <div className="text-sm font-mono font-bold text-[#ef4444]">
                       {formatPrice(item.stop_zone.low)} - {formatPrice(item.stop_zone.high)}
                     </div>
                   </div>

                   <div>
                     <div className="text-[10px] text-[#64748b] font-black uppercase tracking-wider mb-1 flex items-center gap-1">
                       <span className="w-1.5 h-1.5 rounded-full bg-[#a855f7]"></span>
                       HOLDING
                     </div>
                     <div className="text-sm font-mono font-bold text-[#f3e8ff]">
                       {item.holding_period}
                     </div>
                   </div>
                 </div>
              </div>

              {/* Metrics */}
              <div className="flex justify-between text-xs font-mono border-t border-white/5 pt-4">
                <div className="text-[#94a3b8]">RSI: <span className="text-white">{item.rsi}</span></div>
                <div className="text-[#94a3b8]">ADX: <span className="text-white">{item.adx}</span></div>
                <div className="text-[#94a3b8]">RVOL: <span className="text-white">{item.rvol}x</span></div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
