import type { Locale } from "./i18n/copy";

// Hover tooltip text for tracker/list table column headers (Top7, Top100,
// Swing/Trend, Gainers/Losers/Most Active, Theme List, Watchlist). Keyed by
// a semantic column id rather than the (locale-specific) header label text,
// since the same column renders a different label per locale.
export const COLUMN_TOOLTIPS: Record<Locale, Record<string, string>> = {
  en: {
    ticker: "The stock's exchange ticker symbol.",
    dateAdded: "The date this stock was added to the list.",
    sector: "The industry sector the company belongs to.",
    company: "The company's name.",
    price: "The stock's most recent traded price.",
    change1d: "Price change over the last 1 trading day, in percent.",
    change1w: "Price change over the last 1 week, in percent.",
    volume: "Number of shares traded today.",
    volRatio: "Today's volume vs. the recent average — above 1.0 means higher-than-usual trading activity.",
    ema20: "20-day Exponential Moving Average — a short-term smoothed trend line.",
    ema50: "50-day Exponential Moving Average — a medium-term smoothed trend line.",
    ema200: "200-day Exponential Moving Average — a long-term smoothed trend line.",
    status: "The stock's current trend, based on how price and the EMAs are stacked (Bullish / Neutral / Bearish).",
    rsi: "Relative Strength Index (0-100) — a momentum gauge; above 70 is typically overbought, below 30 oversold.",
    pattern: "The most recent candlestick pattern detected on the daily chart.",
    signal: "The system's current trading signal for this stock (Strong / Watch / Wait / Weak).",
    detail: "Click to open the full chart and analysis for this stock.",
    chart: "Click to view the price chart.",
    action: "Remove this stock from your list.",
    marketCap: "Total market value of the company's outstanding shares.",
    score: "The system's composite score for this stock, combining trend, momentum, and volume factors.",
    trackerPool: "Which tracker (Top 100 / Swing) currently includes this stock.",
  },
  tr: {
    ticker: "Hissenin borsa sembolü.",
    dateAdded: "Bu hissenin listeye eklendiği tarih.",
    sector: "Şirketin faaliyet gösterdiği sektör.",
    company: "Şirketin adı.",
    price: "Hissenin en son işlem gördüğü fiyat.",
    change1d: "Son 1 işlem gününde yüzde fiyat değişimi.",
    change1w: "Son 1 haftada yüzde fiyat değişimi.",
    volume: "Bugün işlem gören hisse adedi.",
    volRatio: "Bugünkü hacmin son ortalamaya oranı — 1,0'ın üzeri, normalden fazla işlem hacmi anlamına gelir.",
    ema20: "20 günlük Üssel Hareketli Ortalama — kısa vadeli düzeltilmiş trend çizgisi.",
    ema50: "50 günlük Üssel Hareketli Ortalama — orta vadeli düzeltilmiş trend çizgisi.",
    ema200: "200 günlük Üssel Hareketli Ortalama — uzun vadeli düzeltilmiş trend çizgisi.",
    status: "Fiyatın ve EMA'ların sıralanışına göre hissenin şu anki trend durumu (Yükseliş / Nötr / Düşüş).",
    rsi: "Göreceli Güç Endeksi (0-100) — bir momentum göstergesi; 70 üzeri genelde aşırı alım, 30 altı aşırı satım sayılır.",
    pattern: "Günlük grafikte tespit edilen en son mum formasyonu.",
    signal: "Sistemin bu hisse için şu anki işlem sinyali (Güçlü / İzle / Bekle / Zayıf).",
    detail: "Bu hissenin tam grafiğini ve analizini açmak için tıklayın.",
    chart: "Fiyat grafiğini görüntülemek için tıklayın.",
    action: "Bu hisseyi listenizden kaldırın.",
    marketCap: "Şirketin toplam piyasa değeri (dolaşımdaki hisse × fiyat).",
    score: "Trend, momentum ve hacim faktörlerini birleştiren sistemin bu hisse için toplam puanı.",
    trackerPool: "Bu hissenin şu anda hangi listede (Top 100 / Swing) yer aldığı.",
  },
  es: {
    ticker: "El símbolo bursátil de la acción.",
    dateAdded: "La fecha en que esta acción se agregó a la lista.",
    sector: "El sector industrial al que pertenece la empresa.",
    company: "El nombre de la empresa.",
    price: "El precio más reciente al que se negoció la acción.",
    change1d: "Variación del precio en el último día de negociación, en porcentaje.",
    change1w: "Variación del precio en la última semana, en porcentaje.",
    volume: "Número de acciones negociadas hoy.",
    volRatio: "Volumen de hoy frente al promedio reciente — por encima de 1,0 indica actividad de negociación superior a la habitual.",
    ema20: "Media Móvil Exponencial de 20 días — una línea de tendencia suavizada a corto plazo.",
    ema50: "Media Móvil Exponencial de 50 días — una línea de tendencia suavizada a medio plazo.",
    ema200: "Media Móvil Exponencial de 200 días — una línea de tendencia suavizada a largo plazo.",
    status: "La tendencia actual de la acción, según cómo se alinean el precio y las EMA (Alcista / Neutral / Bajista).",
    rsi: "Índice de Fuerza Relativa (0-100) — un indicador de momentum; por encima de 70 suele ser sobrecompra, por debajo de 30 sobreventa.",
    pattern: "El patrón de velas más reciente detectado en el gráfico diario.",
    signal: "La señal de trading actual del sistema para esta acción (Fuerte / Vigilar / Esperar / Débil).",
    detail: "Haz clic para abrir el gráfico completo y el análisis de esta acción.",
    chart: "Haz clic para ver el gráfico de precios.",
    action: "Eliminar esta acción de tu lista.",
    marketCap: "Valor total de mercado de las acciones en circulación de la empresa.",
    score: "La puntuación compuesta del sistema para esta acción, combinando tendencia, momentum y volumen.",
    trackerPool: "En qué lista (Top 100 / Swing) se encuentra actualmente esta acción.",
  },
  fr: {
    ticker: "Le symbole boursier de l'action.",
    dateAdded: "La date à laquelle cette action a été ajoutée à la liste.",
    sector: "Le secteur d'activité de l'entreprise.",
    company: "Le nom de l'entreprise.",
    price: "Le dernier prix négocié de l'action.",
    change1d: "Variation du prix sur le dernier jour de bourse, en pourcentage.",
    change1w: "Variation du prix sur la dernière semaine, en pourcentage.",
    volume: "Nombre d'actions échangées aujourd'hui.",
    volRatio: "Volume du jour par rapport à la moyenne récente — au-dessus de 1,0 signifie une activité supérieure à la normale.",
    ema20: "Moyenne Mobile Exponentielle sur 20 jours — une ligne de tendance lissée à court terme.",
    ema50: "Moyenne Mobile Exponentielle sur 50 jours — une ligne de tendance lissée à moyen terme.",
    ema200: "Moyenne Mobile Exponentielle sur 200 jours — une ligne de tendance lissée à long terme.",
    status: "La tendance actuelle de l'action, selon l'alignement du prix et des EMA (Haussière / Neutre / Baissière).",
    rsi: "Indice de Force Relative (0-100) — un indicateur de momentum ; au-dessus de 70, généralement en surachat, en dessous de 30, en survente.",
    pattern: "Le dernier motif de chandelier détecté sur le graphique journalier.",
    signal: "Le signal de trading actuel du système pour cette action (Fort / À surveiller / Attendre / Faible).",
    detail: "Cliquez pour ouvrir le graphique complet et l'analyse de cette action.",
    chart: "Cliquez pour voir le graphique des prix.",
    action: "Retirer cette action de votre liste.",
    marketCap: "Valeur boursière totale des actions en circulation de l'entreprise.",
    score: "Le score composite du système pour cette action, combinant tendance, momentum et volume.",
    trackerPool: "Dans quelle liste (Top 100 / Swing) se trouve actuellement cette action.",
  },
  pt: {
    ticker: "O símbolo de negociação da ação.",
    dateAdded: "A data em que esta ação foi adicionada à lista.",
    sector: "O setor da indústria ao qual a empresa pertence.",
    company: "O nome da empresa.",
    price: "O preço mais recente negociado da ação.",
    change1d: "Variação do preço no último dia de negociação, em porcentagem.",
    change1w: "Variação do preço na última semana, em porcentagem.",
    volume: "Número de ações negociadas hoje.",
    volRatio: "Volume de hoje em relação à média recente — acima de 1,0 indica atividade de negociação acima do normal.",
    ema20: "Média Móvel Exponencial de 20 dias — uma linha de tendência suavizada de curto prazo.",
    ema50: "Média Móvel Exponencial de 50 dias — uma linha de tendência suavizada de médio prazo.",
    ema200: "Média Móvel Exponencial de 200 dias — uma linha de tendência suavizada de longo prazo.",
    status: "A tendência atual da ação, com base em como o preço e as EMAs estão alinhados (Alta / Neutro / Baixa).",
    rsi: "Índice de Força Relativa (0-100) — um indicador de momentum; acima de 70 geralmente é sobrecompra, abaixo de 30 é sobrevenda.",
    pattern: "O padrão de candle mais recente detectado no gráfico diário.",
    signal: "O sinal de negociação atual do sistema para esta ação (Forte / Observar / Aguardar / Fraco).",
    detail: "Clique para abrir o gráfico completo e a análise desta ação.",
    chart: "Clique para ver o gráfico de preços.",
    action: "Remover esta ação da sua lista.",
    marketCap: "Valor total de mercado das ações em circulação da empresa.",
    score: "A pontuação composta do sistema para esta ação, combinando tendência, momentum e volume.",
    trackerPool: "Em qual lista (Top 100 / Swing) esta ação está atualmente.",
  },
  id: {
    ticker: "Simbol saham di bursa.",
    dateAdded: "Tanggal saham ini ditambahkan ke daftar.",
    sector: "Sektor industri tempat perusahaan ini berada.",
    company: "Nama perusahaan.",
    price: "Harga saham yang terakhir diperdagangkan.",
    change1d: "Perubahan harga selama 1 hari perdagangan terakhir, dalam persen.",
    change1w: "Perubahan harga selama 1 minggu terakhir, dalam persen.",
    volume: "Jumlah saham yang diperdagangkan hari ini.",
    volRatio: "Volume hari ini dibandingkan rata-rata terkini — di atas 1,0 berarti aktivitas perdagangan lebih tinggi dari biasanya.",
    ema20: "Exponential Moving Average 20 hari — garis tren yang dihaluskan untuk jangka pendek.",
    ema50: "Exponential Moving Average 50 hari — garis tren yang dihaluskan untuk jangka menengah.",
    ema200: "Exponential Moving Average 200 hari — garis tren yang dihaluskan untuk jangka panjang.",
    status: "Tren saham saat ini, berdasarkan susunan harga dan EMA (Bullish / Netral / Bearish).",
    rsi: "Relative Strength Index (0-100) — indikator momentum; di atas 70 biasanya jenuh beli, di bawah 30 jenuh jual.",
    pattern: "Pola candlestick terbaru yang terdeteksi pada grafik harian.",
    signal: "Sinyal trading sistem saat ini untuk saham ini (Kuat / Pantau / Tunggu / Lemah).",
    detail: "Klik untuk membuka grafik lengkap dan analisis saham ini.",
    chart: "Klik untuk melihat grafik harga.",
    action: "Hapus saham ini dari daftar Anda.",
    marketCap: "Total nilai pasar dari saham beredar perusahaan.",
    score: "Skor gabungan sistem untuk saham ini, menggabungkan faktor tren, momentum, dan volume.",
    trackerPool: "Daftar mana (Top 100 / Swing) yang saat ini menyertakan saham ini.",
  },
};

export function getColumnTooltip(locale: Locale, key: string | null | undefined): string | undefined {
  if (!key) return undefined;
  return COLUMN_TOOLTIPS[locale]?.[key] ?? COLUMN_TOOLTIPS.en[key];
}
