// Auto-generated ticker-to-sector mapping from themeData.ts
// Updated: 2026-06-01T02:43:27.626Z

export const TICKER_SECTOR_MAP: Record<string, string> = {
  "AAPL": "Technology",
  "MSFT": "Technology",
  "GOOGL": "Technology",
  "META": "Technology",
  "AMZN": "Technology",
  "NVDA": "Technology",
  "AMD": "Technology",
  "AVGO": "Technology",
  "QCOM": "Technology",
  "TXN": "Technology",
  "MU": "Technology",
  "LRCX": "Technology",
  "AMAT": "Technology",
  "KLAC": "Technology",
  "MRVL": "Technology",
  "MCHP": "Technology",
  "SWKS": "Technology",
  "MPWR": "Technology",
  "ON": "Technology",
  "WOLF": "Technology",
  "SMCI": "Technology",
  "ARM": "Technology",
  "ADI": "Technology",
  "STX": "Technology",
  "WDC": "Technology",
  "SNDK": "Technology",
  "COHR": "Technology",
  "LITE": "Technology",
  "ORCL": "Technology",
  "CRM": "Technology",
  "ADBE": "Technology",
  "NOW": "Technology",
  "INTU": "Technology",
  "WDAY": "Technology",
  "TEAM": "Technology",
  "ZM": "Technology",
  "DDOG": "Technology",
  "MDB": "Technology",
  "SNOW": "Technology",
  "HUBS": "Technology",
  "VEEV": "Technology",
  "BILL": "Technology",
  "GTLB": "Technology",
  "TTD": "Technology",
  "SMAR": "Technology",
  "ZS": "Technology",
  "PANW": "Technology",
  "CRWD": "Technology",
  "FTNT": "Technology",
  "OKTA": "Technology",
  "S": "Technology",
  "CYBR": "Technology",
  "PLTR": "Technology",
  "MSTR": "Technology",
  "IBM": "Technology",
  "ANSS": "Technology",
  "CDNS": "Technology",
  "SNPS": "Technology",
  "CSCO": "Technology",
  "NET": "Technology",
  "AKAM": "Technology",
  "ANET": "Technology",
  "JNPR": "Technology",
  "NTAP": "Technology",
  "DELL": "Technology",
  "INTC": "Technology",
  "TSM": "Technology",
  "GLW": "Technology",
  "GRMN": "Technology",
  "KEYS": "Technology",
  "VRT": "Technology",
  "NFLX": "Communication Services",
  "DIS": "Communication Services",
  "SPOT": "Communication Services",
  "ROKU": "Communication Services",
  "WBD": "Communication Services",
  "PARA": "Communication Services",
  "T": "Communication Services",
  "VZ": "Communication Services",
  "TMUS": "Communication Services",
  "CHTR": "Communication Services",
  "CMCSA": "Communication Services",
  "NOK": "Communication Services",
  "ERIC": "Communication Services",
  "VOD": "Communication Services",
  "AMX": "Communication Services",
  "EA": "Communication Services",
  "TTWO": "Communication Services",
  "RBLX": "Communication Services",
  "SNAP": "Communication Services",
  "PINS": "Communication Services",
  "MTCH": "Communication Services",
  "TKO": "Communication Services",
  "OMC": "Communication Services",
  "BIDU": "Communication Services",
  "EBAY": "Consumer Discretionary",
  "ETSY": "Consumer Discretionary",
  "W": "Consumer Discretionary",
  "BABA": "Consumer Discretionary",
  "TSLA": "Consumer Discretionary",
  "F": "Consumer Discretionary",
  "GM": "Consumer Discretionary",
  "RIVN": "Consumer Discretionary",
  "LCID": "Consumer Discretionary",
  "HD": "Consumer Discretionary",
  "LOW": "Consumer Discretionary",
  "WSM": "Consumer Discretionary",
  "MCD": "Consumer Discretionary",
  "SBUX": "Consumer Discretionary",
  "CMG": "Consumer Discretionary",
  "YUM": "Consumer Discretionary",
  "QSR": "Consumer Discretionary",
  "DPZ": "Consumer Discretionary",
  "WEN": "Consumer Discretionary",
  "NKE": "Consumer Discretionary",
  "LULU": "Consumer Discretionary",
  "RL": "Consumer Discretionary",
  "PVH": "Consumer Discretionary",
  "TPR": "Consumer Discretionary",
  "VFC": "Consumer Discretionary",
  "UAA": "Consumer Discretionary",
  "BKNG": "Consumer Discretionary",
  "ABNB": "Consumer Discretionary",
  "EXPE": "Consumer Discretionary",
  "MAR": "Consumer Discretionary",
  "HLT": "Consumer Discretionary",
  "H": "Consumer Discretionary",
  "RCL": "Consumer Discretionary",
  "CCL": "Consumer Discretionary",
  "NCLH": "Consumer Discretionary",
  "LYV": "Consumer Discretionary",
  "FUN": "Consumer Discretionary",
  "TJX": "Consumer Discretionary",
  "ROST": "Consumer Discretionary",
  "FIVE": "Consumer Discretionary",
  "DLTR": "Consumer Discretionary",
  "DG": "Consumer Discretionary",
  "UBER": "Consumer Discretionary",
  "LYFT": "Consumer Discretionary",
  "DASH": "Consumer Discretionary",
  "TSCO": "Consumer Discretionary",
  "SIG": "Consumer Discretionary",
  "ANF": "Consumer Discretionary",
  "CAVA": "Consumer Discretionary",
  "CAR": "Consumer Discretionary",
  "PG": "Consumer Staples",
  "CL": "Consumer Staples",
  "KMB": "Consumer Staples",
  "CHD": "Consumer Staples",
  "KO": "Consumer Staples",
  "PEP": "Consumer Staples",
  "MNST": "Consumer Staples",
  "STZ": "Consumer Staples",
  "BF.B": "Consumer Staples",
  "MDLZ": "Consumer Staples",
  "GIS": "Consumer Staples",
  "CPB": "Consumer Staples",
  "HRL": "Consumer Staples",
  "CAG": "Consumer Staples",
  "SJM": "Consumer Staples",
  "K": "Consumer Staples",
  "HSY": "Consumer Staples",
  "TSN": "Consumer Staples",
  "PM": "Consumer Staples",
  "MO": "Consumer Staples",
  "BTI": "Consumer Staples",
  "WMT": "Consumer Staples",
  "COST": "Consumer Staples",
  "TGT": "Consumer Staples",
  "KR": "Consumer Staples",
  "SFM": "Consumer Staples",
  "EL": "Consumer Staples",
  "ULTA": "Consumer Staples",
  "COTY": "Consumer Staples",
  "ADM": "Consumer Staples",
  "BG": "Consumer Staples",
  "MOS": "Consumer Staples",
  "CTVA": "Consumer Staples",
  "SYY": "Consumer Staples",
  "LLY": "Healthcare",
  "JNJ": "Healthcare",
  "ABBV": "Healthcare",
  "MRK": "Healthcare",
  "PFE": "Healthcare",
  "BMY": "Healthcare",
  "AMGN": "Healthcare",
  "REGN": "Healthcare",
  "GILD": "Healthcare",
  "BIIB": "Healthcare",
  "VRTX": "Healthcare",
  "ALNY": "Healthcare",
  "MRNA": "Healthcare",
  "EXEL": "Healthcare",
  "AZN": "Healthcare",
  "NVS": "Healthcare",
  "TAK": "Healthcare",
  "TEVA": "Healthcare",
  "BNTX": "Healthcare",
  "UNH": "Healthcare",
  "ABT": "Healthcare",
  "MDT": "Healthcare",
  "ISRG": "Healthcare",
  "BSX": "Healthcare",
  "SYK": "Healthcare",
  "EW": "Healthcare",
  "ZBH": "Healthcare",
  "HOLX": "Healthcare",
  "BDX": "Healthcare",
  "BAX": "Healthcare",
  "DXCM": "Healthcare",
  "PODD": "Healthcare",
  "INSP": "Healthcare",
  "NVCR": "Healthcare",
  "TMO": "Healthcare",
  "DHR": "Healthcare",
  "A": "Healthcare",
  "IQV": "Healthcare",
  "PKI": "Healthcare",
  "ILMN": "Healthcare",
  "LH": "Healthcare",
  "DGX": "Healthcare",
  "CVS": "Healthcare",
  "CI": "Healthcare",
  "ELV": "Healthcare",
  "HCA": "Healthcare",
  "THC": "Healthcare",
  "ZTS": "Healthcare",
  "IDEXX": "Healthcare",
  "SRPT": "Healthcare",
  "RARE": "Healthcare",
  "ACAD": "Healthcare",
  "JPM": "Financials",
  "BAC": "Financials",
  "WFC": "Financials",
  "C": "Financials",
  "USB": "Financials",
  "TFC": "Financials",
  "PNC": "Financials",
  "RY": "Financials",
  "TD": "Financials",
  "BNS": "Financials",
  "CM": "Financials",
  "BMO": "Financials",
  "HSBC": "Financials",
  "ING": "Financials",
  "BCS": "Financials",
  "SAN": "Financials",
  "BBVA": "Financials",
  "SMFG": "Financials",
  "MUFG": "Financials",
  "NWG": "Financials",
  "LYG": "Financials",
  "GS": "Financials",
  "MS": "Financials",
  "BLK": "Financials",
  "BX": "Financials",
  "KKR": "Financials",
  "APO": "Financials",
  "ARES": "Financials",
  "CG": "Financials",
  "AMP": "Financials",
  "NTRS": "Financials",
  "BK": "Financials",
  "BRK.B": "Financials",
  "AIG": "Financials",
  "MET": "Financials",
  "PRU": "Financials",
  "AFL": "Financials",
  "ALL": "Financials",
  "CB": "Financials",
  "TRV": "Financials",
  "HIG": "Financials",
  "PUK": "Financials",
  "V": "Financials",
  "MA": "Financials",
  "AXP": "Financials",
  "PYPL": "Financials",
  "SQ": "Financials",
  "FIS": "Financials",
  "FISV": "Financials",
  "GPN": "Financials",
  "SCHW": "Financials",
  "IBKR": "Financials",
  "ICE": "Financials",
  "CME": "Financials",
  "CBOE": "Financials",
  "NDAQ": "Financials",
  "COIN": "Financials",
  "HOOD": "Financials",
  "SOFI": "Financials",
  "NU": "Financials",
  "MCO": "Financials",
  "SPGI": "Financials",
  "MSCI": "Financials",
  "RBA": "Financials",
  "RF": "Financials",
  "HBAN": "Financials",
  "CFG": "Financials",
  "FITB": "Financials",
  "MTB": "Financials",
  "KEY": "Financials",
  "XOM": "Energy",
  "CVX": "Energy",
  "SHEL": "Energy",
  "TTE": "Energy",
  "BP": "Energy",
  "EQNR": "Energy",
  "COP": "Energy",
  "EOG": "Energy",
  "OXY": "Energy",
  "DVN": "Energy",
  "FANG": "Energy",
  "HES": "Energy",
  "APA": "Energy",
  "MRO": "Energy",
  "MTDR": "Energy",
  "CHRD": "Energy",
  "CRGY": "Energy",
  "EQT": "Energy",
  "MUR": "Energy",
  "CNQ": "Energy",
  "CVE": "Energy",
  "SU": "Energy",
  "OVV": "Energy",
  "PBR": "Energy",
  "EC": "Energy",
  "SLB": "Energy",
  "HAL": "Energy",
  "BKR": "Energy",
  "OII": "Energy",
  "MPC": "Energy",
  "VLO": "Energy",
  "PSX": "Energy",
  "PARR": "Energy",
  "KMI": "Energy",
  "WMB": "Energy",
  "ET": "Energy",
  "EPD": "Energy",
  "MPLX": "Energy",
  "OKE": "Energy",
  "TRGP": "Energy",
  "DTM": "Energy",
  "KNTK": "Energy",
  "ENB": "Energy",
  "TRP": "Energy",
  "LNG": "Energy",
  "GLNG": "Energy",
  "FLNG": "Energy",
  "WDS": "Energy",
  "VAL": "Energy",
  "RIG": "Energy",
  "TDW": "Energy",
  "AROC": "Energy",
  "BTU": "Energy",
  "ARCH": "Energy",
  "BEP": "Energy",
  "CCJ": "Energy",
  "TPL": "Energy",
  "FCX": "Materials",
  "SCCO": "Materials",
  "TECK": "Materials",
  "RIO": "Materials",
  "BHP": "Materials",
  "VALE": "Materials",
  "MT": "Materials",
  "NEM": "Materials",
  "GOLD": "Materials",
  "AEM": "Materials",
  "WPM": "Materials",
  "RGLD": "Materials",
  "FNV": "Materials",
  "KGC": "Materials",
  "GFI": "Materials",
  "AU": "Materials",
  "SSRM": "Materials",
  "PAAS": "Materials",
  "FSM": "Materials",
  "ALB": "Materials",
  "SQM": "Materials",
  "LTHM": "Materials",
  "SGML": "Materials",
  "LIN": "Materials",
  "APD": "Materials",
  "CE": "Materials",
  "SHW": "Materials",
  "ECL": "Materials",
  "PPG": "Materials",
  "DD": "Materials",
  "DOW": "Materials",
  "LYB": "Materials",
  "EMN": "Materials",
  "CF": "Materials",
  "NTR": "Materials",
  "NUE": "Materials",
  "STLD": "Materials",
  "X": "Materials",
  "AA": "Materials",
  "CENX": "Materials",
  "MLM": "Materials",
  "VMC": "Materials",
  "CRH": "Materials",
  "EXP": "Materials",
  "IP": "Materials",
  "PKG": "Materials",
  "WRK": "Materials",
  "NEXA": "Materials",
  "BVN": "Materials",
  "BA": "Industrials",
  "LMT": "Industrials",
  "RTX": "Industrials",
  "NOC": "Industrials",
  "GD": "Industrials",
  "HII": "Industrials",
  "TDG": "Industrials",
  "AXON": "Industrials",
  "LHX": "Industrials",
  "KTOS": "Industrials",
  "GE": "Industrials",
  "GEV": "Industrials",
  "CMI": "Industrials",
  "TDY": "Industrials",
  "AME": "Industrials",
  "CAT": "Industrials",
  "DE": "Industrials",
  "EMR": "Industrials",
  "ETN": "Industrials",
  "ROK": "Industrials",
  "PH": "Industrials",
  "IR": "Industrials",
  "XYL": "Industrials",
  "DOV": "Industrials",
  "HUBB": "Industrials",
  "HWM": "Industrials",
  "WAB": "Industrials",
  "ALSN": "Industrials",
  "HON": "Industrials",
  "MMM": "Industrials",
  "UNP": "Industrials",
  "CSX": "Industrials",
  "NSC": "Industrials",
  "CNI": "Industrials",
  "UPS": "Industrials",
  "FDX": "Industrials",
  "ODFL": "Industrials",
  "PCAR": "Industrials",
  "DAL": "Industrials",
  "UAL": "Industrials",
  "AAL": "Industrials",
  "LUV": "Industrials",
  "ALK": "Industrials",
  "CHRW": "Industrials",
  "EXPD": "Industrials",
  "WM": "Industrials",
  "RSG": "Industrials",
  "CTAS": "Industrials",
  "ROP": "Industrials",
  "FAST": "Industrials",
  "GWW": "Industrials",
  "ROL": "Industrials",
  "PWR": "Industrials",
  "FLR": "Industrials",
  "J": "Industrials",
  "PRIM": "Industrials",
  "MTZ": "Industrials",
  "STRL": "Industrials",
  "URI": "Industrials",
  "AL": "Industrials",
  "AER": "Industrials",
  "WSC": "Industrials",
  "BR": "Industrials",
  "VRSK": "Industrials",
  "DNB": "Industrials",
  "AIR": "Industrials",
  "SYM": "Industrials",
  "FTAI": "Industrials",
  "NEE": "Utilities",
  "DUK": "Utilities",
  "SO": "Utilities",
  "AEP": "Utilities",
  "EXC": "Utilities",
  "PEG": "Utilities",
  "XEL": "Utilities",
  "ED": "Utilities",
  "ES": "Utilities",
  "WEC": "Utilities",
  "ETR": "Utilities",
  "CMS": "Utilities",
  "DTE": "Utilities",
  "EVRG": "Utilities",
  "OGE": "Utilities",
  "AEE": "Utilities",
  "ATO": "Utilities",
  "EIX": "Utilities",
  "FE": "Utilities",
  "PPL": "Utilities",
  "NGG": "Utilities",
  "VST": "Utilities",
  "CEG": "Utilities",
  "NRG": "Utilities",
  "AES": "Utilities",
  "SRE": "Utilities",
  "PCG": "Utilities",
  "NI": "Utilities",
  "OGS": "Utilities",
  "CNP": "Utilities",
  "AWK": "Utilities",
  "WTRG": "Utilities",
  "CWT": "Utilities",
  "MSEX": "Utilities",
  "CWEN": "Utilities",
  "AY": "Utilities",
  "BE": "Utilities",
  "PLD": "Real Estate",
  "O": "Real Estate",
  "VICI": "Real Estate",
  "EPRT": "Real Estate",
  "GOOD": "Real Estate",
  "GTY": "Real Estate",
  "EQIX": "Real Estate",
  "AMT": "Real Estate",
  "DLR": "Real Estate",
  "CCI": "Real Estate",
  "SBAC": "Real Estate",
  "EGP": "Real Estate",
  "FR": "Real Estate",
  "BXP": "Real Estate",
  "VNO": "Real Estate",
  "SPG": "Real Estate",
  "MAC": "Real Estate",
  "KIM": "Real Estate",
  "REG": "Real Estate",
  "FRT": "Real Estate",
  "KRG": "Real Estate",
  "AVB": "Real Estate",
  "EQR": "Real Estate",
  "MAA": "Real Estate",
  "UDR": "Real Estate",
  "CPT": "Real Estate",
  "NMI": "Real Estate",
  "AMH": "Real Estate",
  "WELL": "Real Estate",
  "VTR": "Real Estate",
  "HR": "Real Estate",
  "OHI": "Real Estate",
  "PSA": "Real Estate",
  "EXR": "Real Estate",
  "CUBE": "Real Estate",
  "LSI": "Real Estate",
  "IRM": "Real Estate",
  "ARE": "Real Estate",
  "CBRE": "Real Estate",
  "HST": "Real Estate",
  "LAMR": "Real Estate",
  "SUI": "Real Estate",
  "RHP": "Real Estate",
  "PEB": "Real Estate",
  "WY": "Real Estate",
  "PCH": "Real Estate",
  "DHI": "Real Estate"
};

export const SECTOR_SUMMARY = {
  "Technology": {
    count: 71,
    themes: ["Mega-cap Platform & Cloud", "Semiconductors & Hardware", "Software & Cloud Applications", "Cybersecurity", "AI & Data", "Infrastructure & Networking", "Hardware & Devices"]
  },
  "Communication Services": {
    count: 24,
    themes: ["Social & Search", "Streaming & Entertainment", "Telecom - US", "Telecom - Global", "Gaming", "Interactive & Social", "Advertising", "EM Digital"]
  },
  "Consumer Discretionary": {
    count: 50,
    themes: ["E-commerce & Marketplace", "Automotive & EV", "Home Improvement", "Fast Food & Restaurant", "Apparel & Footwear", "Travel & Leisure", "Retail", "Delivery & Gig", "Luxury & Other"]
  },
  "Consumer Staples": {
    count: 34,
    themes: ["Household & Personal Care", "Beverages", "Food & Snacks", "Tobacco", "Retail / Wholesale", "Beauty & Cosmetics", "Agriculture", "Food Service Distribution"]
  },
  "Healthcare": {
    count: 52,
    themes: ["Large-cap Pharma - US", "Large-cap Pharma - Global", "Medical Devices & Equipment", "Diagnostics & Services", "Health Insurance & Services", "Veterinary", "Biotech Emerging"]
  },
  "Financials": {
    count: 70,
    themes: ["Money-Center Banks - US", "Money-Center Banks - Canada", "Money-Center Banks - Europe/Asia", "Investment Banking & Asset Management", "Insurance", "Payment Networks", "Brokerage & Exchange", "Fintech & Crypto", "Data & Ratings", "Business Services", "Regional Banks - US"]
  },
  "Energy": {
    count: 57,
    themes: ["Integrated Majors - US", "Integrated Majors - International", "E&P - US", "E&P - Canada", "E&P - International/EM", "Oilfield Services", "Refining & Marketing", "Midstream & Pipeline - US", "Midstream & Pipeline - Canada", "LNG & Shipping", "Offshore & Support", "Coal", "Renewables", "Uranium (nükleer talep)", "TPL (arazi & enerji)"]
  },
  "Materials": {
    count: 49,
    themes: ["Copper & Base Metals", "Diversified Mining", "Gold Mining", "Silver Mining", "Lithium & Battery Metals", "Industrial Gases", "Specialty Chemicals", "Agriculture Chemicals", "Steel & Aluminum", "Construction Materials", "Paper & Packaging", "Other"]
  },
  "Industrials": {
    count: 68,
    themes: ["Aerospace & Defense", "Engines & Power", "Precision Instruments & Test", "Machinery & Equipment", "Conglomerate", "Transportation - Rail", "Transportation - Parcel & Air", "Transportation - Trucking", "Transportation - Airlines", "Freight Brokerage & Logistics", "Staffing & Business Services", "Construction & Engineering", "Leasing & Rental", "Commercial Services", "Aviation MRO", "Other"]
  },
  "Utilities": {
    count: 37,
    themes: ["Electric - Regulated", "Electric - UK/International", "Electric - Clean/Nuclear (AI Power Demand)", "Gas & Multi-Utility", "Water", "Renewable / YieldCo", "Bloom Energy (fuel cell)"]
  },
  "Real Estate": {
    count: 47,
    themes: ["Diversified REIT", "Data Center REIT", "Industrial / Logistics REIT", "Office REIT", "Retail REIT", "Residential REIT", "Healthcare REIT", "Storage REIT", "Specialty REIT", "Timber REIT", "Hotels"]
  }
};
