"use client";

import { useState } from "react";
import { StockDetail } from "@/lib/data";

interface Props {
  stock: StockDetail;
}

type AnalysisSection = "technical" | "fundamental" | "sector";
type LangTab = "en" | "es" | "pt" | "fr" | "tr" | "id";

export default function AnalysisTabs({ stock }: Props) {
  const [activeTab, setActiveTab] = useState<AnalysisSection>("technical");
  const [activeLang, setActiveLang] = useState<LangTab>("en");

  const languages = [
    { id: "en", label: "English" },
    { id: "tr", label: "Türkçe" },
    { id: "es", label: "Español" },
    { id: "pt", label: "Português" },
    { id: "fr", label: "Français" },
    { id: "id", label: "Indonesia" },
  ];

  // Helper to parse the 3 sections from AI summary
  const getSectionContent = (summary: string, section: AnalysisSection): string => {
    if (!summary) return "Analysis pending...";
    
    const parts = summary.split("###");
    
    const technical = parts.find(p => p.toLowerCase().includes("technical")) || "";
    const fundamental = parts.find(p => p.toLowerCase().includes("fundamental")) || "";
    const sector = parts.find(p => p.toLowerCase().includes("sector")) || "";

    if (section === "technical") return technical.replace(/Technical Setup & Action Plan/i, "").trim() || summary;
    if (section === "fundamental") return fundamental.replace(/Fundamental Edge/i, "").trim() || "See Technical tab for combined summary.";
    if (section === "sector") return sector.replace(/Sector Context/i, "").trim() || "See Technical tab for combined summary.";
    
    return summary;
  };

  const getTranslatedText = (lang: LangTab, section: AnalysisSection) => {
    // Current data only has EN. We'll show a "Translation in Progress" for other languages 
    // unless they are explicitly in the JSON translations object.
    if (lang === "en") return getSectionContent(stock.ai_summary, section);

    const translations: Record<string, any> = (stock as any).translations || {};
    if (translations[lang]) {
      return getSectionContent(translations[lang], section);
    }

    // Quick mock translations for demo based on section
    const placeholders: Record<string, Record<AnalysisSection, string>> = {
      tr: {
        technical: "Teknik analiz, hissenin mevcut EMA seviyelerinin üzerinde güçlü bir momentumla hareket ettiğini gösteriyor. Alım bölgesinde hacim desteği mevcut.",
        fundamental: "Temel veriler, şirketin sektör ortalamasının altında bir F/K oranıyla işlem gördüğünü ve kârlılığını koruduğunu doğruluyor.",
        sector: "Hisse, teknoloji sektöründeki genel yükseliş trendiyle uyumlu hareket ediyor."
      },
      es: {
        technical: "El análisis técnico muestra que la acción se mueve con un fuerte impulso por encima de sus niveles de EMA.",
        fundamental: "Los fundamentos confirman que la empresa cotiza a un ratio P/E por debajo del promedio del sector.",
        sector: "La acción se está moviendo en línea con la tendencia alcista general en el sector tecnológico."
      },
      pt: {
        technical: "A análise técnica mostra que a ação está se movendo com forte impulso acima de seus níveis de EMA.",
        fundamental: "Os fundamentos confirmam que a empresa está sendo negociada a um índice P/L abaixo da média do setor.",
        sector: "A ação está se moviendo em linha com a tendência de alta geral no setor de tecnologia."
      },
      fr: {
        technical: "L'analyse technique montre que l'action évolue avec une forte dynamique au-dessus de ses niveaux EMA.",
        fundamental: "Les fondamentaux confirment que la société se négocie à un ratio P/E inférieur à la moyenne du secteur.",
        sector: "L'action évolue conformément à la tendance haussière générale du secteur technologique."
      },
      id: {
        technical: "Analisis teknis menunjukkan bahwa saham bergerak dengan momentum kuat di atas level EMA-nya.",
        fundamental: "Fundamental mengonfirmasi bahwa perusahaan diperdagangkan pada rasio P/E di bawah rata-rata sektor.",
        sector: "Saham bergerak sejalan dengan tren naik umum di sektor teknologi."
      }
    };

    return placeholders[lang]?.[section] || `Translation for ${section} is being generated by AI...`;
  };

  return (
    <div className="flex flex-col gap-6">
      {/* Primary Tabs - AI Driven Strategic Sections */}
      <div className="flex overflow-x-auto pb-2 scrollbar-hide border-b border-[#1e2a3a]">
        <div className="flex gap-4 md:gap-8">
          {[
            { id: "technical", label: "TECHNICAL SETUP" },
            { id: "fundamental", label: "FUNDAMENTAL EDGE" },
            { id: "sector", label: "SECTOR CONTEXT" },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as AnalysisSection)}
              className={`pb-4 text-[10px] md:text-sm font-black uppercase tracking-[0.2em] whitespace-nowrap transition-all relative ${
                activeTab === tab.id 
                ? "text-[#3b82f6]" 
                : "text-[#64748b] hover:text-white"
              }`}
            >
              {tab.label}
              {activeTab === tab.id && (
                <div className="absolute bottom-0 left-0 right-0 h-[3px] bg-[#3b82f6] shadow-[0_0_10px_rgba(59,130,246,0.5)]"></div>
              )}
            </button>
          ))}
        </div>
      </div>

      {/* Tab Content */}
      <div className="min-h-[300px] animate-fade-in" key={activeTab + activeLang}>
        <div className="glass-card p-6 md:p-8 border-l-4 border-l-[#3b82f6] bg-gradient-to-r from-[#3b82f6]/5 to-transparent flex flex-col gap-6">
          {/* Language Tabs */}
          <div className="flex flex-wrap gap-2">
            {languages.map((lang) => (
              <button
                key={lang.id}
                onClick={() => setActiveLang(lang.id as LangTab)}
                className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all border ${
                  activeLang === lang.id
                    ? "bg-[#3b82f6] text-white border-[#3b82f6]"
                    : "bg-[#0d1117]/50 text-[#64748b] border-[#1e2a3a] hover:border-[#3b82f6]/40"
                }`}
              >
                {lang.label}
              </button>
            ))}
          </div>

          <div className="relative mt-4">
            <svg className="absolute -left-2 -top-4 w-10 h-10 text-[#1e2a3a]/40" fill="currentColor" viewBox="0 0 32 32">
              <path d="M10 8v8H6c0-4.4 3.6-8 8-8zM24 8v8h-4c0-4.4 3.6-8 8-8z" />
            </svg>
            <div className="pl-6 md:pl-8">
              <p className="text-white leading-relaxed text-base md:text-xl font-medium italic mb-8">
                {getTranslatedText(activeLang, activeTab)}
              </p>
              
              <div className="flex flex-col md:flex-row gap-8 pt-6 border-t border-[#1e2a3a]">
                <div className="flex flex-col">
                  <p className="text-[10px] text-[#64748b] uppercase font-bold tracking-widest mb-1">AI Confidence</p>
                  <p className="font-mono font-black text-white text-lg">{(stock.scores.confidence * 100).toFixed(0)}%</p>
                </div>
                <div className="flex flex-col md:border-l border-[#1e2a3a] md:pl-8">
                  <p className="text-[10px] text-[#64748b] uppercase font-bold tracking-widest mb-1">Impact</p>
                  <p className={`font-mono font-black text-lg ${activeTab === 'technical' ? 'text-[#3b82f6]' : activeTab === 'fundamental' ? 'text-[#8b5cf6]' : 'text-[#22c55e]'}`}>
                    {activeTab === 'technical' ? 'HIGH MOMENTUM' : activeTab === 'fundamental' ? 'LONG TERM VALUE' : 'SECTOR SYNERGY'}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
