import { cn } from '@/lib/utils'
import type { AIText } from '@/types/finma514'
import { TrendingUp, TrendingDown, Minus, AlertTriangle, Target, Info, Lightbulb } from 'lucide-react'

interface AITextPanelProps {
  aiText: AIText
  compact?: boolean
}

const FIELDS: {
  key: keyof AIText
  label: string
  icon: React.ElementType
  color: string
}[] = [
  { key: 'market_context',     label: 'Piyasa Bağlamı',   icon: Info,         color: 'text-finma-primary' },
  { key: 'interest_zone_text', label: 'İlgi Bölgesi',     icon: Target,       color: 'text-finma-cyan' },
  { key: 'scenario_bull',      label: '🐂 Boğa Senaryosu', icon: TrendingUp,   color: 'text-finma-green' },
  { key: 'scenario_bear',      label: '🐻 Ayı Senaryosu',  icon: TrendingDown, color: 'text-finma-red' },
  { key: 'scenario_neutral',   label: '⚖️ Nötr Senaryo',  icon: Minus,        color: 'text-finma-yellow' },
  { key: 'risk_reference',     label: 'Risk Referansı',   icon: AlertTriangle, color: 'text-finma-yellow' },
  { key: 'strategy_note',      label: 'Strateji Notu',    icon: Lightbulb,    color: 'text-finma-purple' },
]

export function AITextPanel({ aiText, compact = false }: AITextPanelProps) {
  if (!aiText) return null

  const fields = compact ? FIELDS.slice(0, 4) : FIELDS

  return (
    <div className="space-y-2">
      {/* Generated by badge */}
      {aiText.generated_by && (
        <div className="flex items-center gap-1.5 mb-3">
          <span className="w-1.5 h-1.5 rounded-full bg-finma-green animate-pulse-slow" />
          <span className="text-[10px] text-finma-text-dim font-mono">
            {aiText.generated_by.includes('gemini') ? 'Gemini AI' : 'Şablon'} — Legal-Safe ✓
          </span>
        </div>
      )}

      {fields.map(({ key, label, icon: Icon, color }) => {
        const text = aiText[key] as string
        if (!text || key === 'generated_by') return null
        return (
          <div key={key} className="bg-finma-bg rounded-lg p-3 border border-finma-border/60">
            <div className="flex items-center gap-1.5 mb-1.5">
              <Icon className={cn('w-3 h-3 shrink-0', color)} />
              <span className="text-[10px] font-semibold text-finma-text-dim uppercase tracking-wider">
                {label}
              </span>
            </div>
            <p className="text-xs text-finma-text leading-relaxed">{text}</p>
          </div>
        )
      })}

      {/* Yasal uyarı */}
      <p className="text-[9px] text-finma-text-dim/60 italic pt-1 border-t border-finma-border/30">
        Bu içerik bilgilendirme amaçlıdır ve yatırım tavsiyesi niteliği taşımaz.
        Tüm yatırım kararları kişisel sorumluluğunuzdadır.
      </p>
    </div>
  )
}
